---
- name: Install Nginx
  hosts: localhost
  become: yes

  tasks:
    - name: Set locale to UTF-8
      become: yes
      command: update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
